### ISSUE TITLE
Change the sequence of files.

### ISSUE THREAD

**Issue by baltechies** [fooman/speedsteradvanced#11]
Its changed the sequence of file rendering. Please suggest.

**Comment by fooman** [comment]
@baltechies this is intentional - for details you can see my presentation on this when Speedster Advanced was introduced https://www.youtube.com/watch?v=DfU5733mstg

These 
js
js_css

will be sorted before
skin_js
skin_css

You can run the included Theme Optimiser to help with sorting everything into the right bucket.
